name: Create and publish a package
on:
  push:
    branches: ['release/**']
defaults:
  run:
    working-directory: ./TestClassLib
jobs:
  build-and-push-image:
    env:
      BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}
      BUILD_CONFIGURATION: Release
      USER: ${{ github.actor }}
      NUGET_ARTIFACT_FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      PROJECTS_TO_BUILD: 'TestClassLib.csproj'
      PROJECTS_TO_TEST: '**/*.Tests.csproj'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        source-url: $NUGET_ARTIFACT_FEED_URL
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Output
      run: Write-Host "Present Working Directory '$PWD'"
    - name: .NET Restore
      run: |
        dotnet restore $PROJECTS_TO_BUILD `
          --runtime win-x64
    - name: .NET Build
      run: |
        dotnet build $PROJECTS_TO_BUILD `
          --runtime win-x64 `
          --no-restore `
          --configuration $BUILD_CONFIGURATION `
          /p:AssemblyVersion=$BUILD_NUMBER
    # - name: .NET Test
    #   run: |
    #     Get-ChildItem ".\test\" -recurse -include "*.csproj" | % {
    #       dotnet test $PROJECTS_TO_TEST `
    #         --runtime win-x64 `
    #         --no-build `
    #         --configuration $BUILD_CONFIGURATION `
    #         --verbosity normal
    #     }
    - name: .NET Pack
      run: |
        dotnet pack `
          --runtime win-x64 `
          --configuration $BUILD_CONFIGURATION
    - name: .NET Nuget Push
      run: |
        dotnet nuget push ${{ github.repository }}.$BUILD_NUMBER.nupkg `
          --source $NUGET_ARTIFACT_FEED_URL
