name: Create and publish a package
on:
  push:
    branches: ['release/**']
defaults:
  run:
    working-directory: ./TestClassLib
jobs:
  build-and-push:
    env:
      MAJOR_VER: 1
      MINOR_VER: 0
      BUILD_VER: ${{ github.run_number }}
      BUILD_CONFIGURATION: Release
      DOTNET_RUNTIME: win-x64
      USER: ${{ github.actor }}
      NUGET_ARTIFACT_FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECTS_TO_BUILD: 'TestClassLib.csproj'
      PROJECTS_TO_TEST: '**/*.Tests.csproj'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        source-url: ${{ env.NUGET_ARTIFACT_FEED_URL }}
    - name: Output
      run: |
        Write-Host "Present Working Directory '$PWD'"
        Write-Host "Build Number '${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ env.BUILD_VER }}'"
        Write-Host "Build Config '${{ env.BUILD_CONFIGURATION }}'"
        Write-Host "Build Projects '${{ env.PROJECTS_TO_BUILD }}'"
    - name: .NET Restore
      run: |
        dotnet restore `
          --runtime ${{ env.DOTNET_RUNTIME }} `
          ${{ env.PROJECTS_TO_BUILD }}
    - name: .NET Build
      run: |
        dotnet build `
          --no-restore `
          --runtime ${{ env.DOTNET_RUNTIME }} `
          --configuration ${{ env.BUILD_CONFIGURATION }} `
          -p:AssemblyVersion=${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ env.BUILD_VER }} `
          -p:Version=${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ env.BUILD_VER }} `
          ${{ env.PROJECTS_TO_BUILD }}
    # - name: .NET Test
    #   run: |
    #     Get-ChildItem ".\test\" -recurse -include "*.csproj" | % {
    #       dotnet test `
    #         --runtime ${{ env.DOTNET_RUNTIME }} `
    #         --no-build `
    #         --configuration ${{ env.BUILD_CONFIGURATION }} `
    #         $PROJECTS_TO_TEST
    #     }
    - name: .NET Pack
      run: |
        dotnet pack `
          -p:PackageVersion ${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ env.BUILD_VER }} `
          --configuration ${{ env.BUILD_CONFIGURATION }} `
          --runtime ${{ env.DOTNET_RUNTIME }} `
          --output ${{ env.GITHUB_WORKSPACE }}/out `
          ${{ env.PROJECTS_TO_BUILD }}
    - name: .NET Nuget Push
      run: |
        dotnet nuget push `
          ${{ env.GITHUB_WORKSPACE }}/out/*.${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ env.BUILD_VER }}.nupkg `
          --source ${{ env.NUGET_ARTIFACT_FEED_URL }}
